### ISSUE TITLE
Error when read card

### ISSUE THREAD

**Issue by seekerquoc** [russss/python-emv#15]
Hello Sir,
when i tried get data of card, it alwayls show this error for any command of emvtool
Can u check and help me fix it?

Thanks
emvtool -l debug info
INFO:emv.transmission:Connected to reader
DEBUG:emv.transmission:Tx: [00 A4 04 00 0E 31 50 41 59 2E 53 59 53 2E 44 44 46 30 31 00]
DEBUG:emv.transmission:Rx: [], SW1: 6a, SW2: 82
Traceback (most recent call last):
  File "/usr/local/bin/emvtool", line 11, in <module>
    load_entry_point('emv==1.0.9', 'console_scripts', 'emvtool')()
  File "/usr/local/lib/python3.6/dist-packages/emv/command/client.py", line 46, in run
    cli(obj={})
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.6/dist-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.6/dist-packages/emv/command/client.py", line 131, in info
    apps = card.list_applications()
  File "/usr/local/lib/python3.6/dist-packages/emv/card.py", line 30, in list_applications
    res = self.tp.exchange(SelectCommand("1PAY.SYS.DDF01"))
  File "/usr/local/lib/python3.6/dist-packages/emv/transmission.py", line 52, in exchange
    res = RAPDU.unmarshal(data + [sw1, sw2])
  File "/usr/local/lib/python3.6/dist-packages/emv/protocol/response.py", line 32, in unmarshal
    raise obj
emv.protocol.response.ErrorResponse: <ErrorResponse: "Wrong parameter(s) P1 P2; file not found">
emv@ubuntu:~$

**Comment by russss** [comment]
Hi,

I think this should be fixed in version 1.0.10. Your card uses an older method for selecting apps, which I hadn't implemented, and it took me a while to find my card reader to test it with!
