### ISSUE TITLE
Shiny new barclays card (old one runs out Oct 31st 2021) - can't generate cap

### ISSUE THREAD

**Issue by castaway** [russss/python-emv#20]
emvtool doesn't seem to like this new card (was fine with the old one), it outputs a stacktrace followed by:

```KeyError: (159, 85)```

listapps outputs this:
```┌Applications──────────┬────────────────────────┐
│ Index │ Label        │ ADF                    │
├───────┼──────────────┼────────────────────────┤
│ 0     │ "LINK ATM"   │ [A0 00 00 00 29 10 10] │
│ 1     │ "Visa Debit" │ [A0 00 00 00 03 10 10] │
│ 2     │ "BARCLAYS"   │ [A0 00 00 00 03 80 02] │
└───────┴──────────────┴────────────────────────┘
```

Anything else I can try/poke? Where are the KeyErrors defined?

**Comment by russss** [comment]
It is - here: https://pypi.org/project/emv/1.0.12/

**Comment by kababoom** [comment]
Thanks, needed manual uninstall first 👍 
emvtool version
1.0.12

But not supported card still unfortunately, cap generates an error:

![image](https://user-images.githubusercontent.com/16404944/142214317-00c043dc-2d36-4f81-b0d2-061e370b4871.png)


Traceback (most recent call last):
  File "/usr/local/bin/emvtool", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/emv/command/client.py", line 46, in run
    cli(obj={})
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/emv/command/client.py", line 190, in cap
    click.echo(card.generate_cap_value(pin, challenge=challenge, value=amount))
  File "/usr/local/lib/python3.9/site-packages/emv/card.py", line 190, in generate_cap_value
    return get_cap_value(resp, app_data[Tag.IPB], psn)
KeyError: (159, 86)

**Comment by russss** [comment]
I've moved this to issue #20.
