### ISSUE TITLE
Issuer Proprietary Bitmap still not found

### ISSUE THREAD

**Issue by russss** [russss/python-emv#21]
Thanks, needed manual uninstall first 👍 
emvtool version
1.0.12

But not supported card still unfortunately, cap generates an error:

![image](https://user-images.githubusercontent.com/16404944/142214317-00c043dc-2d36-4f81-b0d2-061e370b4871.png)

Traceback (most recent call last):
  File "/usr/local/bin/emvtool", line 8, in <module>
    sys.exit(run())
  File "/usr/local/lib/python3.9/site-packages/emv/command/client.py", line 46, in run
    cli(obj={})
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 829, in __call__
    return self.main(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 782, in main
    rv = self.invoke(ctx)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1259, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 1066, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/usr/local/lib/python3.9/site-packages/click/core.py", line 610, in invoke
    return callback(*args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/click/decorators.py", line 21, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/usr/local/lib/python3.9/site-packages/emv/command/client.py", line 190, in cap
    click.echo(card.generate_cap_value(pin, challenge=challenge, value=amount))
  File "/usr/local/lib/python3.9/site-packages/emv/card.py", line 190, in generate_cap_value
    return get_cap_value(resp, app_data[Tag.IPB], psn)
KeyError: (159, 86)

_Originally posted by @kababoom in https://github.com/russss/python-emv/issues/20#issuecomment-971608167_

**Comment by russss** [comment]
@kababoom can you run `emvtool info` and see if "Issuer Proprietary Bitmap" is listed anywhere in the response?

**Comment by kababoom** [comment]
@russss Thank you ...

Here's the full output, I think I covered all personal info.

![Screenshot 2021-11-19 at 13 08 55](https://user-images.githubusercontent.com/16404944/142621747-0592ff02-1f23-4f1c-badb-639b8aa00f60.png)

**Comment by CharlesButcher** [comment]
I have the same error for my Nationwide debit card, and "Issuer Proprietary Bitmap" doesn't appear in `emvtool info`.

Both my Barclays debit cards work fine with v1.0.13 and show the bitmap field as expected.

**Comment by russss** [comment]
I've now pushed a new version, 1.0.14, which uses a default IPB if there isn't one present on the card. You'll see a warning if this is used, because I can't guarantee that the resulting code will actually work.

Feel free to file a new issue if this still doesn't work, although I can't guarantee that I'll be able to fix it in this case as it will likely require some bank-specific rubbish.

**Comment by CharlesButcher** [comment]
Thanks for trying this. With my Nationwide card 1.0.14 gives a nine-digit CAP (plus the warning!). I tried the first eight digits, but no joy.

**Comment by kababoom** [comment]
@russss Finally found time to try 1.0.14 but also 9 digit cap + warning here with my LBG card unfortunately.. 

Not sure where to get the IPB from, I could not find anything online. I got an old card which I experiment with, anything I can try?

Thank you....
