### ISSUE TITLE
emvtool info fails to display card info and errors

### ISSUE THREAD

**Issue by idnorton** [russss/python-emv#3]
When checking for card info, I get an error:
```
iann-laptop ~ # emvtool info
Traceback (most recent call last):
  File "/usr/local/bin/emvtool", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/emv/command/client.py", line 37, in run
    EMVClient().run()
  File "/usr/local/lib/python2.7/dist-packages/emv/command/client.py", line 75, in run
    self.args.func()
  File "/usr/local/lib/python2.7/dist-packages/emv/command/client.py", line 92, in card_info
    apps = card.list_applications()
  File "/usr/local/lib/python2.7/dist-packages/emv/card.py", line 24, in list_applications
    res = self.tp.exchange(SelectCommand('1PAY.SYS.DDF01'))
  File "/usr/local/lib/python2.7/dist-packages/emv/transmission.py", line 53, in exchange
    res = RAPDU.unmarshal(data + [sw1, sw2])
  File "/usr/local/lib/python2.7/dist-packages/emv/protocol/response.py", line 34, in unmarshal
    raise obj
emv.protocol.response.ErrorResponse: <ErrorResponse: "Unknown error: 6d 00">
```

I guess that's back from one of the underlying libs. pcsc_scan tells me:
```
Possibly identified card (using /usr/share/pcsc/smartcard_list.txt):
3B 6E 00 00 80 31 80 66 B0 84 0C 01 6E 01 83 00 90 00
        Nordea (a Skandinavian bank) eID card
        http://linux.fi/wiki/Nordea_eID
```

Not sure if that info is helpful or not :/ Is there any other info I can provide to assist with debugging? 

I'm afraid my Python is pretty much zero :(

Thanks for any help, Ian.

**Comment by idnorton** [comment]
Ah, mildly more info with debug:
```
iann-laptop ~ # emvtool -l debug info
INFO:emv.transmission:Connected to reader
DEBUG:emv.transmission:Tx: [00 A4 04 00 0E 31 50 41 59 2E 53 59 53 2E 44 44 46 30 31 00]
DEBUG:emv.transmission:Rx: [], SW1: 61, SW2: 1c
DEBUG:emv.transmission:Tx: [00 C0 00 00 1C]
DEBUG:emv.transmission:Rx: [], SW1: 6d, SW2: 00
Traceback (most recent call last):
  File "/usr/local/bin/emvtool", line 11, in <module>
    sys.exit(run())
  File "/usr/local/lib/python2.7/dist-packages/emv/command/client.py", line 37, in run
    EMVClient().run()
  File "/usr/local/lib/python2.7/dist-packages/emv/command/client.py", line 75, in run
    self.args.func()
  File "/usr/local/lib/python2.7/dist-packages/emv/command/client.py", line 92, in card_info
    apps = card.list_applications()
  File "/usr/local/lib/python2.7/dist-packages/emv/card.py", line 24, in list_applications
    res = self.tp.exchange(SelectCommand('1PAY.SYS.DDF01'))
  File "/usr/local/lib/python2.7/dist-packages/emv/transmission.py", line 53, in exchange
    res = RAPDU.unmarshal(data + [sw1, sw2])
  File "/usr/local/lib/python2.7/dist-packages/emv/protocol/response.py", line 34, in unmarshal
    raise obj
emv.protocol.response.ErrorResponse: <ErrorResponse: "Unknown error: 6d 00">
```

**Comment by idnorton** [comment]
Interestingly @castaway has the exact same ATR and hers is working fine.

**Comment by idnorton** [comment]
So resolved this using the Gemalto PC Twin Reader instead of the Omnikey 5321v2.
