### ISSUE TITLE
emvtool info fails with `assert connection.getProtocol() == connection.T0_protocol AssertionError

### ISSUE THREAD

**Issue by hamstah** [russss/python-emv#8]
Hi,
Tried with a ACS ACR122U and followed https://ludovicrousseau.blogspot.com/2013/11/linux-nfc-driver-conflicts-with-ccid.html to get pcscd to run.

```
$ emvtool info
Traceback (most recent call last):
  File "/home/hamstah/repos/nfc/venv/bin/emvtool", line 10, in <module>
    sys.exit(run())
  File "/home/hamstah/repos/nfc/venv/lib/python3.6/site-packages/emv/command/client.py", line 46, in run
    cli(obj={})
  File "/home/hamstah/repos/nfc/venv/lib/python3.6/site-packages/click/core.py", line 764, in __call__
    return self.main(*args, **kwargs)
  File "/home/hamstah/repos/nfc/venv/lib/python3.6/site-packages/click/core.py", line 717, in main
    rv = self.invoke(ctx)
  File "/home/hamstah/repos/nfc/venv/lib/python3.6/site-packages/click/core.py", line 1137, in invoke
    return _process_result(sub_ctx.command.invoke(sub_ctx))
  File "/home/hamstah/repos/nfc/venv/lib/python3.6/site-packages/click/core.py", line 956, in invoke
    return ctx.invoke(self.callback, **ctx.params)
  File "/home/hamstah/repos/nfc/venv/lib/python3.6/site-packages/click/core.py", line 555, in invoke
    return callback(*args, **kwargs)
  File "/home/hamstah/repos/nfc/venv/lib/python3.6/site-packages/click/decorators.py", line 17, in new_func
    return f(get_current_context(), *args, **kwargs)
  File "/home/hamstah/repos/nfc/venv/lib/python3.6/site-packages/emv/command/client.py", line 109, in info
    card = get_reader(ctx.obj['reader'])
  File "/home/hamstah/repos/nfc/venv/lib/python3.6/site-packages/emv/command/client.py", line 38, in get_reader
    return Card(smartcard.System.readers()[reader].createConnection())
  File "/home/hamstah/repos/nfc/venv/lib/python3.6/site-packages/emv/card.py", line 16, in __init__
    self.tp = TransmissionProtocol(connection)
  File "/home/hamstah/repos/nfc/venv/lib/python3.6/site-packages/emv/transmission.py", line 17, in __init__
    assert connection.getProtocol() == connection.T0_protocol
AssertionError
```

Tried a few different cards (visa, mastercard) with the same result

Thanks

**Comment by russss** [comment]
Thanks for the report - looks like your card reader behaves a bit differently. This bug should be fixed in version 1.0.7 which I've just released.
